url: https://stevenlwcz.github.io
title: A Blog on The GDB Python API and ARM Assembler
email: StevenLwcz1@virginmedia.com
description: #>
  Creating posts about the GDB Python API and ARM Assembler.
github_username: StevenLwcz
github_url: https://github.com/StevenLwcz/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

