url: https://stevenlwcz.github.io
title: Blogs on The GDB Python API
email: StevenLwcz1@virginmedia.com
description: #>
  Creating blogs about the GDB Python API starting with the TUI Window
  and Arm Assembler.
github_username: StevenLwcz
github_url: https://github.com/StevenLwcz/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

