title: Blogs on The GDB Python API
github_username: StevenLwcz
github_url: https://github.com/StevenLwcz/
url: https://stevenlwcz.github.io

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

